services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./.:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./docker/php/
    volumes:
      - ./.:/var/www/html
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=root
