services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - '8002:80'
    volumes:
      - ./.:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./docker/php/
    volumes:
      - ./.:/var/www/html
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project
      MYSQL_PASSWORD: password
volumes:
  db_data:
